### ISSUE TITLE
Include a calculator for Euro Truck & American Truck Simulators

### ISSUE THREAD

**Issue by Tyfui90** [dinex86/FOV-Calculator#2]

**Comment by groybe** [comment]
Do you know how Euro Truck handles fov?
I think it might be standard horizontal degrees. If this is the case than it will be the same as Project CARS.

**Comment by Tyfui90** [comment]
Yeah from the looks of it ESTS2 and ATS both use horizontal fov.

**Comment by Tyfui90** [comment]
Does @dinex86 still monitor this repo? I see he hasnt merged your PR yet. Could you change the text for ""hFov, Project CARS 1 & 2" to "hFov, Project CARS 1 & 2, ATS, ETS2" inside script.js in your MR?

**Comment by dinex86** [comment]
Oh sorry, I havn't been notified about any issues or pull requests. I will take a look at the PR this week!

**Comment by dinex86** [comment]
Included games :)

**Comment by Tyfui90** [comment]
Looks like its working as expected with the changes. Thanks!
