### ISSUE TITLE
Which Licence is this code released as?

### ISSUE THREAD

**Issue by terrymacdonald** [dinex86/FOV-Calculator#7]
Hi @dinex86,

I've the developer of [DisplayMagician](https://github.com/terrymacdonald/DisplayMagician), a free and open source display manager specially designed for Simracing, and I'd love to use parts of your logic in DisplayMagician (not the code, just the logic). I note you don't have a licence in the github repo, so I wanted to reach out to ask if I could use the logic you have created within DisplayMagician? 

I would make sure you are credited in the DisplayMagician README file, and the release notes.

Is that ok?

Thanks
Terry MacDonald

**Comment by dinex86** [comment]
Hey @terrymacdonald,

thanks for reaching out to me! You can use my logic and the credit in your README is very much appreciated!

Best regards
Markus

**Comment by terrymacdonald** [comment]
Awesome news! Thank you so much for your permission. And especially thank
you so much for inspiring me to add a FOV calc to my code. Keep up the
great work.

Thanks
Terry
