### ISSUE TITLE
Curved screens

### ISSUE THREAD

**Issue by ArnoldsManguzis** [dinex86/FOV-Calculator#9]
Hey all, I know this calculator hasn't been update in a long while, but I'm hoping someone sees this and can either help with the setup or is more knowledgeable on how the calculations for it would be done? Could we have an option for curved UW screens ? I have 3x 34 inch Samsung Odyssey G5's and I'm not sure if this calculator at the moment would accommodate for the curvature of the display? 

Thanks!

**Comment by varbex** [comment]
From what I saw in the code it only handles flat UltraWide, but if you can help with some article explaining how and if curved ultrawide formula for FOV should be i could take a look in the code and see if i can make it work.

**Comment by dzid26** [comment]
You are looking for increasing accuracy in one place but everything else much more distorted and requiring manual tweaking anyway to make it look _somewhat_ realistic.  

The tool and games don't even consider angle between multiple monitors which is probably more pronounced than the monitor curvature itself. - I know that LFS can adjust projection angle between  multiple (flat) screens, but I don't think that's common. (?)

On top of that curved displays are not uniformly curved either. Most curvature is at the center and then it mostly goes straight. At 1m radius the effective screen size as perceived by the user doesn't change much anyway. 

To make it precise, as you imagine, ideally the monitor driver would have to communicate monitor curvature shape to the game engine (again, it's not a simple arc!) to project image properly.  And then you would have to specify angle between monitors or there would be a single agreed angle to be used. 

Anyway, I think you should just pretend the monitor is flat.  

If you really want to see a perceived size difference of the curved display, the quickest would be draw it in a CAD and see what the closest flat monitor value that fits the view. My prediction is that the difference will be small and meaningless as expalned earlier. 

If anyone disagrees, please correct me. 👍

**Comment by varbex** [comment]
Yeah, probably way to dependent on hardware information to provide a correct fov.
